name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rayman-decomp/rayman-ps1-build:main
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - run: pip install -r requirements.txt --break-system-packages
    - name: Cache other dependencies
      id: other-cache
      uses: actions/cache@v4
      with:
        path: |
          SLUS-000.05
          tools/gcc-2.5.7
        key: other-cache
    - if: steps.other-cache.outputs.cache-hit != 'true'
      run: cp /exe/SLUS-000.05 SLUS-000.05
    - if: steps.other-cache.outputs.cache-hit != 'true'
      name: Get gcc
      run:
        wget https://github.com/decompals/old-gcc/releases/download/latest/gcc-2.5.7.tar.gz &&
        mkdir tools/gcc-2.5.7 &&
        tar -xzvf gcc-2.5.7.tar.gz -C tools/gcc-2.5.7
    - name: Extract
      run: make -f mk-splat.mk extract
    - name: Make
      id: make
      run: make -f mk-splat.mk
    - if: always() && steps.make.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        path: build